# Generated by Django 5.1.2 on 2025-03-28 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=255, verbose_name="文件路径")),
                ("file_size", models.PositiveIntegerField(verbose_name="文件大小(字节)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("notebook_count", models.PositiveIntegerField(verbose_name="备份笔记数量")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "备份记录",
                "verbose_name_plural": "备份记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后同步时间"),
                ),
                (
                    "is_syncing",
                    models.BooleanField(default=False, verbose_name="是否正在同步"),
                ),
                ("sync_error", models.TextField(blank=True, verbose_name="同步错误信息")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_status",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步状态",
                "verbose_name_plural": "同步状态",
            },
        ),
    ]
