# Generated by Django 5.1.2 on 2025-06-10 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudBackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_path', models.CharField(max_length=500, verbose_name='云端文件路径')),
                ('cloud_url', models.URLField(max_length=500, verbose_name='云端访问URL')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('notebook_count', models.PositiveIntegerField(verbose_name='备份笔记数量')),
                ('version_name', models.CharField(blank=True, max_length=100, verbose_name='版本名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_backups', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '云版本备份',
                'verbose_name_plural': '云版本备份',
                'ordering': ['-created_at'],
            },
        ),
    ]
