# Generated by Django 5.1.2 on 2025-06-06 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0003_collaborationedit"),
        ("friends", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="群聊名称")),
                ("description", models.TextField(blank=True, verbose_name="群聊描述")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "collaboration_project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_group",
                        to="collaboration.collaborationproject",
                        verbose_name="关联的协作项目",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "群聊",
                "verbose_name_plural": "群聊",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文本消息"),
                            ("system", "系统消息"),
                            ("notification", "通知消息"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发送时间"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="friends.chatgroup",
                        verbose_name="所属群聊",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_group_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "群聊消息",
                "verbose_name_plural": "群聊消息",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="阅读时间"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="friends.groupmessage",
                        verbose_name="消息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息已读状态",
                "verbose_name_plural": "消息已读状态",
                "unique_together": {("message", "user")},
            },
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="read_by",
            field=models.ManyToManyField(
                related_name="read_group_messages",
                through="friends.MessageReadStatus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="已读用户",
            ),
        ),
        migrations.CreateModel(
            name="ChatGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "群主"), ("admin", "管理员"), ("member", "成员")],
                        default="member",
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="加入时间"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否在群内")),
                (
                    "last_read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后阅读时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="friends.chatgroup",
                        verbose_name="所属群聊",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "群聊成员",
                "verbose_name_plural": "群聊成员",
                "ordering": ["joined_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
