# Generated by Django 5.1.2 on 2025-06-11 15:15

from django.db import migrations, models


def convert_admin_to_member(apps, schema_editor):
    """将所有管理员角色转换为普通成员"""
    ChatGroupMember = apps.get_model('friends', 'ChatGroupMember')
    # 将所有admin角色改为member
    ChatGroupMember.objects.filter(role='admin').update(role='member')


def reverse_convert_admin_to_member(apps, schema_editor):
    """反向迁移：不做任何操作，因为我们无法知道哪些成员原来是管理员"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_chatgroup_groupmessage_messagereadstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '好友请求', 'verbose_name_plural': '好友请求'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-created_at'], 'verbose_name': '好友关系', 'verbose_name_plural': '好友关系'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': '私信', 'verbose_name_plural': '私信'},
        ),
        # 先转换数据，再修改字段约束
        migrations.RunPython(convert_admin_to_member, reverse_convert_admin_to_member),
        migrations.AlterField(
            model_name='chatgroupmember',
            name='role',
            field=models.CharField(choices=[('owner', '群主'), ('member', '成员')], default='member', max_length=10, verbose_name='角色'),
        ),
    ]
