# Generated by Django 5.1.2 on 2025-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="user_dark.png", upload_to="profile_pics"),
        ),
    ]
