# Generated by Django 5.1.2 on 2025-06-07 14:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user_dark.png', upload_to=accounts.models.user_avatar_upload_path),
        ),
    ]
