# Generated by Django 5.1.2 on 2025-05-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览量"),
        ),
    ]
