# Generated by Django 5.1.2 on 2025-06-10 10:48

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_notebook_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user', 'parent')},
        ),
    ]
