# Generated by Django 5.1.2 on 2025-06-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_notebook_uuid_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
