# Generated by Django 5.1.2 on 2025-06-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_alter_category_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
