# Generated by Django 5.1.2 on 2025-06-06 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0001_initial"),
        ("notebooks", "0002_notebook_view_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collaborationlock",
            unique_together={("notebook", "user")},
        ),
    ]
