# Generated by Django 5.1.2 on 2025-06-06 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0002_alter_collaborationlock_unique_together"),
        ("notebooks", "0002_notebook_view_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=500, verbose_name="修改大纲")),
                (
                    "edited_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="修改时间"
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collaboration_edits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="修改者",
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_edits",
                        to="notebooks.notebook",
                        verbose_name="修改的笔记",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="collaboration.collaborationproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "协作修改记录",
                "verbose_name_plural": "协作修改记录",
                "ordering": ["-edited_at"],
            },
        ),
    ]
